
server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/music-inbox?sslMode=VERIFY_IDENTITY
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
